version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands: 
      - echo "Installing dependencies using node20"
      - npm ci
      - echo "Done installing dependencies ==>"
      
  build:
    commands:
      - echo "Building the React project"
      - npm run build
      - echo "Done building the project ==> Exporting artifacts"

artifacts:
  files:
    - '**/*'
  discard-paths: yes  # Asegura que los archivos se coloquen en el root
  base-directory: build  # Cambia "build" por el directorio donde se genera tu build
  secondary-artifacts:
    index-file:
      files:
        - index.html
      discard-paths: yes
      base-directory: build
